services:
  app:
    image:
      willnx/demo-app
    ports:
    - "8000:8000"
    volumes:
      - ./demo:/usr/lib/python3.10/site-packages/demo/
    environment:
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_USERNAME=${DB_USERNAME}
      - DB_HOSTNAME=database
    links:
      - database
  database:
    image:
      willnx/demo-app-db
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
